REFERENCE_WORDS = set([
    # Famous people and groups
    "Jesus Christ",
    "Michael Jackson",
    "Abraham Lincoln",
    "Bill Gates",
    "Leonardo da Vinci",
    "Walt Disney",
    "Adolf Hitler",
    "Stephen Hawking",
    "Lady Gaga",
    "Martin Luther King Jr.",
    "Fidel Castro",
    "The Pope",
    "Audrey Hepburn",
    "Marilyn Monroe",
    "Genghis Khan",
    "Hillary Clinton",
    "Donald Trump",
    "Tom Hanks",
    "Barack Obama",
    "Justin Bieber",
    "Sun Tzu",
    "Warren Buffet",
    "Roger Federer",
    "Rafael Nadal",
    "Babe Ruth",

    # Famous groups
    "The Beatles",
    "Pink Floyd",
    "One Direction",
    "The Black Eyed Peas",
    "Red Hot Chili Peppers",

    # Famous characters
    "Mickey Mouse",
    "Donkey Kong",
    "Robin Hood",
    "Frankenstein",
    "Kevin McCallister",
    "James T. Kirk",
    "Sheldon Cooper",
    "Scooby Doo",

    # Popular movies
    "Harry Potter",
    "The Wizard of Oz",
    "Finding Nemo",
    "Citizen Kane",
    "The Godfather",
    "Toy Story",
    "Inside Out",
    "King Kong",
    "12 Angry Men",
    "The Terminator",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Pulp Fiction",
    "Kung Fu Panda",
    "Mean Girls",

    # Popular TV shows
    "Spongebob Squarepants",
    "Breaking Bad",
    "The Walking Dead",
    "Game of Thrones",
    "Stranger Things",
    "The Big Bang Theory",
    "The Office",

    # Popular games
    "Call of Duty",
    "Angry Birds",
    "League of Legends",
    "Word of Warcraft",
    "Super Smash Bros Melee",

    # Idioms
    "Actions speak louder than words",
    "Ball is in your court",
    "Back to the drawing board",
    "Best of both worlds",
    "Best thing since sliced bread",
    "Don't cry over spilt milk",
    "Kill two birds with one stone",
    "It takes two to tango",
    "A picture is worth a thousand words",
    "Piece of cake",
    "A taste of your own medicine",
    "A blessing in disguise",
    "Bite off more than you can chew",

    # Famous Movie Quotes
    "Frankly, my dear, I don't give a damn.",
    "Here's looking at you, kid.",
    "You're gonna need a bigger boat.",
    "May the Force be with you.",
    "Toto, I've a feeling we're not in Kansas anymore.",
    "I'm going to make him an offer he can't refuse.",
    "Of all the gin joints in all the towns in all the world, she walks into mine.",
    "You talkin' to me?",
    "There's no place like home",
    "The first rule of Fight Club is: You do not talk about Fight Club.",
    "I am your father.",
    "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.",
    "Why so serious?",
    "Houston, we have a problem.",
    "To infinity and beyond!",
    "Live long and prosper.",
    "Resistance is futile.",
    "The line must be drawn here! This far, no further!",
    "I'm sorry, Dave. I'm afraid I can't do that.",
    "The needs of the many outweigh the needs of the few or the one.",
    "I volunteer as tribute!",
    "That's so fetch!",
    "Why so serious?",
    "Wanna know how I got these permanent facial disfigurations?",
    "Who lives in a pineapple under the sea?",
])
